//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendpro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customerid { get; set; }
        public string Customername { get; set; }
        public string Customermobileno { get; set; }
        public Nullable<int> Locationid { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
    }
}
