//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendpro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthsCode
    {
        public int MonthsCodeId { get; set; }
        public string MonthsName { get; set; }
        public string MonthsCode1 { get; set; }
    }
}
