//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendpro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Orderid { get; set; }
        public Nullable<int> Customerid { get; set; }
        public string Imagepath { get; set; }
        public string Status { get; set; }
        public string Ordertext { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> quantity { get; set; }
        public string OrderSerialNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> Locationid { get; set; }
    }
}
