//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendpro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Vendorid { get; set; }
        public string Vendorname { get; set; }
        public string RegisteredMobileno { get; set; }
        public Nullable<int> Locationid { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
    }
}
